-- TABLE: users (For Admin Login)
CREATE TABLE users (
    id                NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR2(255) NOT NULL,
    email             VARCHAR2(255) NOT NULL,
    email_verified_at TIMESTAMP     DEFAULT NULL,
    password          VARCHAR2(255) NOT NULL,
    remember_token    VARCHAR2(100) DEFAULT NULL,
    created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- TABLE: categories (e.g. Fruits, Vegetables)
CREATE TABLE categories (
    id          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(255)   NOT NULL,
    slug        VARCHAR2(255)   NOT NULL,
    description CLOB            DEFAULT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_categories_name UNIQUE (name),
    CONSTRAINT uq_categories_slug UNIQUE (slug)
);

-- TABLE: nutrients (e.g. Protein, Iron, Vitamin C)
CREATE TABLE nutrients (
    id         NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(255) NOT NULL,
    type       VARCHAR2(255) NOT NULL,
    unit       VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_nutrients_name UNIQUE (name)
);

-- TABLE: health_statuses (e.g. Diabetic Friendly, Heart Healthy)
CREATE TABLE health_statuses (
    id         NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(255) NOT NULL,
    slug       VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_health_statuses_name UNIQUE (name),
    CONSTRAINT uq_health_statuses_slug UNIQUE (slug)
);

-- TABLE: foods
CREATE TABLE foods (
    id              NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     NUMBER        NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    scientific_name VARCHAR2(255) DEFAULT NULL,
    description     CLOB          DEFAULT NULL,
    serving_size    VARCHAR2(255) DEFAULT '100g',
    calories        NUMBER(8, 2)  DEFAULT 0,
    image           VARCHAR2(255) DEFAULT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_foods_category_id
        FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

-- TABLE: food_nutrients (Many-to-Many Pivot Table)
CREATE TABLE food_nutrients (
    id          NUMBER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id     NUMBER       NOT NULL,
    nutrient_id NUMBER       NOT NULL,
    amount      NUMBER(8, 2) DEFAULT 0,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_food_nutrients_food_id
        FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE CASCADE,
    CONSTRAINT fk_food_nutrients_nutrient_id
        FOREIGN KEY (nutrient_id) REFERENCES nutrients(id) ON DELETE CASCADE,
    CONSTRAINT uq_food_nutrients_food_nutrient
        UNIQUE (food_id, nutrient_id)
);

-- TABLE: food_health_status (Many-to-Many Pivot Table)
CREATE TABLE food_health_status (
    id               NUMBER    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id          NUMBER    NOT NULL,
    health_status_id NUMBER    NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_fhs_food_id
        FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE CASCADE,
    CONSTRAINT fk_fhs_health_status_id
        FOREIGN KEY (health_status_id) REFERENCES health_statuses(id) ON DELETE CASCADE,
    CONSTRAINT uq_food_health_status
        UNIQUE (food_id, health_status_id)
);
COMMIT;
