
SET DEFINE OFF;
SET SERVEROUTPUT ON;



-- PART 1: VIEWS


-- View 1: vw_food_summary
-- Full food overview with category, nutrient count, health status count
-- Used in: Admin dashboard reports, search summary
CREATE OR REPLACE VIEW vw_food_summary AS
SELECT
    f.id,
    f.name,
    f.scientific_name,
    f.calories,
    f.serving_size,
    f.image,
    f.created_at,
    c.name                                                              AS category_name,
    c.slug                                                              AS category_slug,
    (SELECT COUNT(*) FROM food_nutrients fn WHERE fn.food_id = f.id)   AS nutrient_count,
    (SELECT COUNT(*) FROM food_health_status fhs WHERE fhs.food_id = f.id) AS health_status_count,
    CASE
        WHEN f.calories < 100 THEN 'Very Low'
        WHEN f.calories < 250 THEN 'Low'
        WHEN f.calories < 500 THEN 'Medium'
        WHEN f.calories < 750 THEN 'High'
        ELSE 'Very High'
    END AS calorie_level
FROM foods f
JOIN categories c ON c.id = f.category_id;


-- View 2: vw_category_stats
-- Per-category statistics: food count, avg/min/max calories
CREATE OR REPLACE VIEW vw_category_stats AS
SELECT
    c.id,
    c.name,
    c.slug,
    (SELECT COUNT(*) FROM foods f WHERE f.category_id = c.id)          AS food_count,
    (SELECT ROUND(AVG(f.calories),2) FROM foods f WHERE f.category_id = c.id) AS avg_calories,
    (SELECT MIN(f.calories) FROM foods f WHERE f.category_id = c.id)   AS min_calories,
    (SELECT MAX(f.calories) FROM foods f WHERE f.category_id = c.id)   AS max_calories
FROM categories c;


-- View 3: vw_nutrient_rich_foods
-- Top foods ranked by total number of tracked nutrients
CREATE OR REPLACE VIEW vw_nutrient_rich_foods AS
SELECT
    f.id,
    f.name,
    f.calories,
    c.name                                                             AS category_name,
    (SELECT COUNT(*) FROM food_nutrients fn WHERE fn.food_id = f.id)  AS nutrient_count
FROM foods f
JOIN categories c ON c.id = f.category_id
ORDER BY nutrient_count DESC;



-- PART 2: AUDIT LOG TABLE


CREATE TABLE food_audit_log (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id     NUMBER,
    food_name   VARCHAR2(255),
    action      VARCHAR2(10)  NOT NULL,   -- INSERT, UPDATE, DELETE
    changed_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    old_calories NUMBER(8,2),
    new_calories NUMBER(8,2),
    old_category_id NUMBER,
    new_category_id NUMBER
);

-- PART 3: TRIGGER — Auto-Audit on foods INSERT / UPDATE / DELETE


CREATE OR REPLACE TRIGGER trg_foods_audit
AFTER INSERT OR UPDATE OR DELETE ON foods
FOR EACH ROW
DECLARE
    v_action     VARCHAR2(10);
    v_food_id    NUMBER;
    v_food_name  VARCHAR2(255);
    v_old_cal    NUMBER(8,2);
    v_new_cal    NUMBER(8,2);
    v_old_cat    NUMBER;
    v_new_cat    NUMBER;
BEGIN
    IF INSERTING THEN
        v_action    := 'INSERT';
        v_food_id   := :NEW.id;
        v_food_name := :NEW.name;
        v_old_cal   := NULL;
        v_new_cal   := :NEW.calories;
        v_old_cat   := NULL;
        v_new_cat   := :NEW.category_id;
    ELSIF UPDATING THEN
        v_action    := 'UPDATE';
        v_food_id   := :OLD.id;
        v_food_name := :NEW.name;
        v_old_cal   := :OLD.calories;
        v_new_cal   := :NEW.calories;
        v_old_cat   := :OLD.category_id;
        v_new_cat   := :NEW.category_id;
    ELSE
        v_action    := 'DELETE';
        v_food_id   := :OLD.id;
        v_food_name := :OLD.name;
        v_old_cal   := :OLD.calories;
        v_new_cal   := NULL;
        v_old_cat   := :OLD.category_id;
        v_new_cat   := NULL;
    END IF;

    INSERT INTO food_audit_log (
        food_id, food_name, action,
        old_calories, new_calories,
        old_category_id, new_category_id
    ) VALUES (
        v_food_id, v_food_name, v_action,
        v_old_cal, v_new_cal,
        v_old_cat, v_new_cat
    );
END;
/



-- PART 4: STORED PROCEDURE — SP_SEARCH_FOODS
-- Searches foods by keyword and optional category_id
-- Returns a REF CURSOR that the calling code can iterate over


CREATE OR REPLACE PROCEDURE SP_SEARCH_FOODS (
    p_keyword     IN  VARCHAR2,
    p_category_id IN  NUMBER   DEFAULT NULL,
    p_max_cal     IN  NUMBER   DEFAULT NULL,
    p_result      OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_result FOR
        SELECT
            f.id,
            f.name,
            f.scientific_name,
            f.calories,
            f.serving_size,
            c.name AS category_name
        FROM foods f
        JOIN categories c ON c.id = f.category_id
        WHERE
            (p_keyword IS NULL OR LOWER(f.name) LIKE '%' || LOWER(p_keyword) || '%')
            AND (p_category_id IS NULL OR f.category_id = p_category_id)
            AND (p_max_cal IS NULL OR f.calories <= p_max_cal)
        ORDER BY f.name;
END SP_SEARCH_FOODS;
/

COMMIT;